#!/usr/bin/env node
"use strict";

var https     = require('https');
var inquirer  = require('inquirer');
var program   = require('commander');
var shell     = require('shelljs');
var fs        = require('fs');
var download  = require('download-file');
var OS        = require('opensubtitles-api');

var Subs = new OS({
	useragent: 'OSTestUserAgent'
});

var search   = 'https://yts.ag/api/v2/list_movies.json?query_term=';
var details	 = 'https://yts.ag/api/v2/movie_details.json?movie_id=';

program
	.version('[0.0.1] - MoviesCLI')
	.command('search <movie>')
	.description('Search for a movie')
	.action(function (movie) {
		searchResponse(movie);
	});

// Request using https protocol
var request = function (url, callback) {
	https.get(url, function (response) {
		var data = '';

		response.on('data', function (newData) {
			data += newData;
		});

		response.on('end', function () {
			callback(data);
		});
	});
}

// List movies for search
var searchResponse = function (terms) {
	request(search + encodeURI(terms), function (data) {
		makeList(JSON.parse(data).data.movies, selectQuality);
	});
}

// Make a list
var makeList = function (object, callback) {
	var list = [];

	for (var i in object) {
		list.push({
			'name' : object[i].title_long,
			'value': object[i].id
		});
	}

	inquirer.prompt([
		{
			type    : 'list',
			name    : 'movie',
			message : 'Select your movies: ',
			choices : list,
			default : 0
		}
	]).then(function (answers) {

		if (typeof callback == 'function') {
			callback(answers);
		}
	});
};

// Select a quality for movie
var selectQuality = function (object) {
	var movieID = object.movie;

	request(details + movieID, function (response) {
		response = JSON.parse(response).data;

		var movie    = response.movie;
		var torrents = movie.torrents;
		var list     = [];

		for (var i in torrents) {
			list.push({
				name  : torrents[i].quality,
				value : torrents[i].url 
			})
		};

		inquirer.prompt([
			{
				type    : 'list',
				name    : 'torrent',
				message : 'Available qualities for: ' + movie.title_long,
				choices : list,
				default : 0
			}
		]).then(function (answers) {

			Subs.search({
				sublanguageid : 'pob',
				extensions: ['srt'],
				imdbid : movie.imdb_code
			}).then(function (strs) {

				var subtitle = './subs/' + strs.pb.id + '.srt';

				// Try get a local subtitle
				fs.stat(subtitle, function (err, stats) {
					if (!stats.isFile(subtitle)) {
						// Download
						download(strs.pb.url, {directory : './subs'}, function (err) {
							if (err)
								throw err;
						});
					}
				});

				streamMovie(answers.torrent, subtitle);

			}).catch(function (e) {

				inquirer.prompt([
					{
						type : 'confirm',
						name : 'continue',
						message : 'No subtitles found, stream anyway?',
						default : false
					}
				]).then(function (nosubs) {
					if (!nosubs.continue) {
						console.log('Bye!');
						return;
					}

					streamMovie(answers.torrent);
				});
			});
		});
	});
};

// Stream movie from a torrentURL
var streamMovie = function (torrentURL, substr) {
	var execStr = 'peerflix ' + torrentURL + ' --vlc';

	if (substr != undefined) {
		execStr += ' -- --sub-file=' + substr;
	}

	shell.exec(execStr);
};

program.parse(process.argv);
